name: stagetool-api
channels:
  - conda-forge
dependencies:
  - python==3.14.0
  - numpy==2.5.2
  - pip==26.2.1
  - pip:
      - flask==3.0
      - flask_cors==6.0.5
      - jsonschema==4.19
      - pillow==12.3.0
      - python-dotenv==1.0
      - gunicorn==21.2
      - scikit-image==0.26.0 

